### PR TITLE
add hashable instance for Mod

### PR DESCRIPTION
**Pull request by OliverMadine**
It would be nice for Mod to have a hashable instance to remove some orphaned instances from the [haskell-language-server](https://github.com/haskell/haskell-language-server).

### CODE REVIEW

**Comment by Bodigrim** [comment]
Could you point me to relevant bits of HLS?

**Comment by OliverMadine** [comment]
> Could you point me to relevant bits of HLS?

Yes, actually it's just the instance at [the top of the rename plugin](https://github.com/haskell/haskell-language-server/blob/master/plugins/hls-rename-plugin/src/Ide/Plugin/Rename.hs) from [the recent merge](https://github.com/haskell/haskell-language-server/pull/2809).

**Comment by Bodigrim** [comment]
You can define `instance Hashable UInt` explicitly, not via `instance Hashable Mod`.

**Comment by OliverMadine** [comment]
> You can define `instance Hashable UInt` explicitly, not via `instance Hashable Mod`.

Hmm, we do define `instance Hashable UInt` but we get ` No instance for (Hashable (Mod 2147483648))` without the instance for Mod.

**Comment by Bodigrim** [comment]
You can define `instance Hashable UInt where hashWithSalt s (UInt n) = hashWithSalt s (unMod n)`.

**Comment by OliverMadine** [comment]
> instance Hashable UInt where hashWithSalt s (UInt n) = hashWithSalt s (unMod n)

ah ok, perfect, thank you

**Pull request closed without merging**
